server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///config-repo

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    com.neighbors.authservice: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      show-details: always
