version: '3.8'

services:
  config-server:
    environment:
      SPRING_PROFILES_ACTIVE: native,dev

  auth-service:
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888"
