server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://prod-db-host:5432/authdb
    username: prod_user
    password: prod_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    root: INFO
