spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://config-server:8888"

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    com.neighbors.authservice: TRACE

debug: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, env
  endpoint:
    health:
      show-details: always


